services:

  afterbot:

    container_name: afterbot

    build: .

    restart: unless-stopped

    env_file:
      - .env

    environment:
      - TZ=Europe/Paris

    volumes:
      - .:/app
      - /etc/machine-id:/host/etc/machine-id:ro

    expose:
      - "3000"

    command: node src/index.js

    networks:
      - postgres_default


networks:

  postgres_default:
    external: true