CREATE TABLE IF NOT EXISTS stats_config (
    guild_id BIGINT PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    leaderboard_channel_id BIGINT,
    daily_send_time VARCHAR(5) NOT NULL DEFAULT '20:00',
    last_daily_sent_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE IF EXISTS stats_config
ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS leaderboard_channel_id BIGINT,
ADD COLUMN IF NOT EXISTS daily_send_time VARCHAR(5) NOT NULL DEFAULT '20:00',
ADD COLUMN IF NOT EXISTS last_daily_sent_at TIMESTAMP NULL,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_stats_config_daily_enabled
ON stats_config (enabled, daily_send_time);
